//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public int UserID { get; set; }
        public string ProviderName { get; set; }
        public string ProviderUserID { get; set; }
        public string ProviderUserName { get; set; }
        public Nullable<System.DateTime> LastUsedDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
